### ISSUE TITLE
Windows build

### ISSUE THREAD

**Issue by c33s** [ashald/terraform-provider-yaml#1]
a windows build would be really nice.

**Comment by ashald** [comment]
I just uploaded build for `windows/amd64` for [v2.0.0](https://github.com/Ashald/terraform-provider-yaml/releases/tag/v2.0.0) but I don't have setup to test it - would appreciate feedback!

**Comment by c33s** [comment]
works like charm :)

thank you very much

**Comment by ashald** [comment]
Glad to hear that! 😃
