### ISSUE TITLE
Provider "yaml" not available for installation

### ISSUE THREAD

**Issue by shopskyi** [ashald/terraform-provider-yaml#10]
The terraform can't install YAML provider after download link was changed [(here)](https://github.com/ashald/terraform-provider-yaml/commit/4d4919f1284e9e2302104e020e9f3f345efc7704)

**Error:** Provider "yaml" not available for installation.

How to reproduce:

**main.tf:**
>terraform {
    required_version = "0.11.14"
}
data "yaml_map_of_strings" "rhs_values" {
    input = "${file("<path_to_yaml_file")}"
} 

**bash:**

> wget "https://github.com/ashald/terraform-provider-yaml/releases/download/v2.1.0/terraform-provider-yaml_v2.1.0_$(uname -s | tr '[:upper:]' '[:lower:]')_amd64"
chmod +x ./terraform-provider-yaml*
terraform init

**Comment by PashaIvaniushyn** [comment]
+1, faced the same problem. Please fix the issue.

**Comment by ashald** [comment]
Ooops, that wasn't nice. Fixed now, please try again (I updated the file names in releases and download instructions in the readme).
